apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kibana.fullname" . }}
  labels: {{ include "kibana.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
{{- if .Values.updateStrategy }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name | quote }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- if .Values.kibanaConfig }}
        configchecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.automountToken }}
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
{{- end }}
{{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
{{- end }}
{{- if .Values.serviceAccount }}
      serviceAccount: {{ .Values.serviceAccount }}
{{- end }}
{{- if .Values.hostAliases }}
      hostAliases: {{ toYaml .Values.hostAliases | nindent 8 }}
{{- end }}
      volumes:
        - name: kibana-tokens
          emptyDir: {}
{{- if .Values.elasticsearchCertificateSecret }}
        - name: elasticsearch-certs
          secret:
            secretName: {{ .Values.elasticsearchCertificateSecret | quote }}
{{- end }}
{{- if .Values.kibanaConfig }}
        - name: kibanaconfig
          configMap:
            name: {{ template "kibana.fullname" . }}-config
{{- end }}
{{- range .Values.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName | quote }}
{{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
      initContainers:
{{- if .Values.extraInitContainers }}
{{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
{{- else }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
{{- end }}
{{- end }}
      containers:
        - name: kibana
{{- if .Values.securityContext }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
{{- end }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
{{- if .Values.elasticsearchURL }}
            - name: ELASTICSEARCH_URL
              value: "{{ .Values.elasticsearchURL }}"
{{- else if .Values.elasticsearchHosts }}
            - name: ELASTICSEARCH_HOSTS
              value: "{{ .Values.elasticsearchHosts }}"
{{- end }}
{{- if .Values.elasticsearchCertificateAuthoritiesFile }}
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: "{{ template "kibana.home_dir" . }}/config/certs/{{ .Values.elasticsearchCertificateAuthoritiesFile }}"
{{- end }}
            - name: SERVER_HOST
              value: "{{ .Values.serverHost }}"
            {{- if and .Values.automountToken (not .Values.elasticsearchCredentialSecret) }}
            - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "kibana.fullname" . }}-es-token
                  key: token
                  optional: true
            {{- end }}
{{- if .Values.env }}
{{ toYaml .Values.env | indent 12 }}
{{- end }}
{{- if .Values.envFrom }}
          envFrom:
{{ toYaml .Values.envFrom | indent 12 }}
{{- end }}
          readinessProbe:
{{- if .Values.readinessProbe }}
{{ toYaml .Values.readinessProbe | indent 12 }}
{{- else }}
            exec:
              command:
                - bash
                - -c
                - |
                  #!/usr/bin/env bash -e
                  export NSS_SDB_USE_CACHE=no
                  http () {
                      local path="${1}"
                      set -- -XGET -s --fail -L
                      if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
                        set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
                      fi
                      STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "{{ .Values.protocol }}://localhost:{{ .Values.httpPort }}${path}")
                      if [[ "${STATUS}" -eq 200 ]]; then
                        exit 0
                      fi
                      echo "Error: Got HTTP code ${STATUS} but expected a 200"
                      exit 1
                  }
                  http "{{ .Values.healthCheckPath }}"
{{- end }}
          ports:
            - containerPort: {{ .Values.httpPort }}
{{- if .Values.lifecycle }}
          lifecycle:
{{ toYaml .Values.lifecycle | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: kibana-tokens
              mountPath: {{ template "kibana.home_dir" . }}/config/tokens
              readOnly: true
{{- if .Values.elasticsearchCertificateSecret }}
            - name: elasticsearch-certs
              mountPath: {{ template "kibana.home_dir" . }}/config/certs
              readOnly: true
{{- end }}
{{- range .Values.secretMounts }}
            - name: {{ .name }}
              mountPath: {{ .path }}
{{- if .subPath }}
              subPath: {{ .subPath }}
{{- end }}
{{- end }}
{{- range $path, $config := .Values.kibanaConfig }}
            - name: kibanaconfig
              mountPath: {{ template "kibana.home_dir" . }}/config/{{ $path }}
              subPath: {{ $path }}
{{- end }}
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
{{- if .Values.extraContainers }}
{{- if eq "string" (printf "%T" .Values.extraContainers) }}
{{ tpl .Values.extraContainers . | indent 10 }}
{{- else }}
{{ toYaml .Values.extraContainers | indent 10 }}
{{- end }}
{{- end }}
